"""
Config Generator
Generate configuration files for tunneling tools
"""

from pathlib import Path


class ProxychainsConfigGenerator:
    """Generate proxychains configuration files"""

    def __init__(self, output_dir: Path):
        """
        Initialize config generator

        Args:
            output_dir: Output directory for config files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def generate(self, socks_port: int, socks_version: int = 5) -> Path:
        """
        Generate proxychains configuration

        Args:
            socks_port: SOCKS proxy port
            socks_version: SOCKS version (4 or 5, default: 5)

        Returns:
            Path to generated config file
        """
        config_file = self.output_dir / "proxychains.conf"

        config = self._get_config_template(socks_port, socks_version)

        with open(config_file, 'w') as f:
            f.write(config)

        return config_file

    def _get_config_template(self, socks_port: int, socks_version: int) -> str:
        """
        Get proxychains config template

        Args:
            socks_port: SOCKS proxy port
            socks_version: SOCKS version

        Returns:
            Config file contents
        """
        return f"""# Proxychains configuration for SSH tunnel
# Generated by SSH Tunneling Framework

# Strict chain - all proxies must be online
strict_chain

# Proxy DNS requests through the tunnel
proxy_dns

# Timeouts (in milliseconds)
tcp_read_time_out 15000
tcp_connect_time_out 8000

# ProxyList format:
# type  host  port  [user pass]
[ProxyList]
socks{socks_version} 127.0.0.1 {socks_port}
"""

    def generate_with_chain(self, proxies: list) -> Path:
        """
        Generate proxychains config with proxy chain

        Args:
            proxies: List of proxy dicts with 'type', 'host', 'port'

        Returns:
            Path to generated config file
        """
        config_file = self.output_dir / "proxychains_chain.conf"

        config = """# Proxychains configuration with proxy chain
# Generated by SSH Tunneling Framework

strict_chain
proxy_dns
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
"""

        for proxy in proxies:
            proxy_type = proxy.get('type', 'socks5')
            host = proxy.get('host', '127.0.0.1')
            port = proxy.get('port', 1080)

            config += f"{proxy_type} {host} {port}\n"

        with open(config_file, 'w') as f:
            f.write(config)

        return config_file


class SSHConfigGenerator:
    """Generate SSH configuration files"""

    def __init__(self, output_dir: Path):
        """
        Initialize SSH config generator

        Args:
            output_dir: Output directory for config files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def generate_jump_host_config(
            self,
            jump_host: str,
            jump_user: str,
            target_host: str,
            target_user: str
    ) -> Path:
        """
        Generate SSH config for jump host

        Args:
            jump_host: Jump host IP/hostname
            jump_user: SSH username for jump host
            target_host: Target host IP/hostname
            target_user: SSH username for target

        Returns:
            Path to generated config file
        """
        config_file = self.output_dir / "ssh_jump_config"

        config = f"""# SSH Jump Host Configuration
# Generated by SSH Tunneling Framework

Host jump
    HostName {jump_host}
    User {jump_user}

Host target
    HostName {target_host}
    User {target_user}
    ProxyJump jump

# Usage:
# ssh -F {config_file} target
"""

        with open(config_file, 'w') as f:
            f.write(config)

        return config_file